fix: add app layer rule
feature-sliced/eslint-config pull request #109
Opened 2024-04-14 19:49 UTC by rokashkovvd

## Description

## References

## Checklist
- [ ] Description added
- [ ] Self-reviewed
- [ ] CI pass

2024-04-18 18:14 UTC, illright requested changes
Hi, thanks for the PR! I think it's not directly written in the docs that segments in app can import each other, but technically I don't think there should be any restrictions, so maybe we should update the docs as well.

Could you please also remove the now unused variable `sharedLayerRule`? Then this would be good to merge

2024-04-20 08:16 UTC, Krakazybik requested changes
Thank you for the PR. Could you please add a short description to your PR? Additionally, it would be great to include this case in positive tests.

2024-04-21 16:35 UTC, illright commented
Thanks for the update! I agree with @Krakazybik here, this should probably also be reflected in tests. Let me know if you encounter any issues

2024-04-30 07:40 UTC, Krakazybik approved these changes
Thank you for your contribution!

2024-04-30 22:19 UTC, illright approved these changes

2024-04-30 22:19 UTC, merged

2024-04-30 22:25 UTC, illright commented
Released in 0.1.1, thank you!