feat(public-api): God Mode(IDDQD) for publicAPI
feature-sliced/eslint-config pull request #88
Opened 2022-02-04 18:43 UTC by Krakazybik

## Description
Добавлен чит (префикс _) для игнорирования правила publicAPI
## References
https://github.com/feature-sliced/eslint-config/discussions/75#discussioncomment-2056223
## Checklist
- [ ] Description added
- [ ] Self-reviewed
- [ ] CI pass

2022-02-05 12:10 UTC, azinit commented
😏 

![image](https://user-images.githubusercontent.com/42924400/152641482-0032b8b0-661c-499c-8b1e-8976c4cca7f6.png)

2022-02-05 12:36 UTC, azinit requested changes
Кажется произошло недопонимание)))

2022-02-05 12:36 UTC, azinit commented on rules/public-api/index.js
> +                     */
Пасхалочки пошли))

2022-02-05 12:36 UTC, azinit commented on rules/public-api/index.js
> +                    `**/_*/**`
[`issue(critical):`](https://conventionalcomments.org/) **Так, а вот тут прям проблема)**

Либо я как-то не так изъяснился, либо в целом недопоняли - но такой хак предполагался только для кастомных сегментов (!!) в shared

Просто потому что доставать сегменты из любых других слоев - в целом нелегально
(только если мы не делаем это "изнутри" слайса - но там либо реэкспорты, либо лайт конфиг помогут - там хоть какие сегменты плоди, в "внешних" импортах это не отразится 🤔 )

https://github.com/feature-sliced/eslint-config/discussions/75#discussioncomment-2108885

[`suggestion(critical):`](https://conventionalcomments.org/) Поэтому, боюсь надо переделать чисто под shared, т.к. чит достаточно опасный, и контекст треда был именно про shared [(доброжелательно советую перечитать)](https://github.com/feature-sliced/eslint-config/discussions/75#discussioncomment-2086186)

[`thoughts:`](https://conventionalcomments.org/) Если же у тебя есть мысли по поводу того, как это может быть применимо и для других слоев - дай пож знать ))

2022-02-05 12:36 UTC, azinit commented on rules/public-api/index.js
> +                    `**/_*/**`
[`thoughts:`](https://conventionalcomments.org/) Мб ты спутал с [другим тредом](https://github.com/feature-sliced/eslint-config/discussions/75#discussioncomment-2108880) - про `layer-slices`

Вот там да - было предложение сделать подобное для всех слоев, т.к. встречается далеко не только в pages, но и в entities


![image](https://user-images.githubusercontent.com/42924400/152642336-e149915d-0093-40f5-bec0-8ce4193e242d.png)

2022-02-05 12:36 UTC, azinit commented on rules/public-api/lite.js
> +                    `**/_*/**`,
Ну и тут тоже собсна переделать бы)

2022-02-05 14:54 UTC, Krakazybik commented on rules/public-api/index.js
> +                    `**/_*/**`
причём тут shared если референс на трэд с _route и предложением сделать легальным всё, что начинается на _

2022-02-05 15:02 UTC, Krakazybik commented on rules/public-api/index.js
> +                    `**/_*/**`
именно по этому я считаю, что нужно заводить ишьюсы, чтобы не было недопонимания и путаницы

2022-02-05 15:58 UTC, azinit commented on rules/public-api/index.js
> +                    `**/_*/**`
> причём тут shared если референс на трэд с _route и предложением сделать легальным всё, что начинается на _

Так даже в референсе написано)

![image](https://user-images.githubusercontent.com/42924400/152648962-3220aebf-d6e4-4d31-b788-77d6f040a800.png)

2022-02-05 15:58 UTC, azinit commented on rules/public-api/index.js
> +                    `**/_*/**`
> именно по этому я считаю, что нужно заводить ишьюсы, чтобы не было недопонимания и путаницы

Да, мы уже обсуждали)

2022-02-05 16:02 UTC, Krakazybik commented on rules/public-api/index.js
> +                    `**/_*/**`
я тебя не понимаю, этот пр не по shared

2022-02-05 16:09 UTC, azinit commented on rules/public-api/index.js
> +                    `**/_*/**`
@Krakazybik Отписал в ЛС 🤔

2022-02-05 21:18 UTC, azinit reviewed
Получше, но есть еще вопросы)

2022-02-05 21:18 UTC, azinit commented on rules/public-api/lite.js
> +                    `**/?(*)shared/*(${FS_SEGMENTS_REG})`,
А поч для лайта пришлось эти строчки править?

2022-02-05 21:18 UTC, azinit commented on rules/public-api/lite.test.js
> +          import { Four } from "shared/_note/three/four";
Хм, а можно сделать так, чтобы `_**` только на сегменты влиял?

Т.е. чтобы вариант `shared/_note/two` был валиден, но `shared/_note/three/four` уже нет, т.к. это хоть как нарушение PublicAPI 🤔 
(тип у нас же `_***` не для абсолютного читмода PublicAPI, а для того - чтобы сегменты самые разные по неймингу были 🤔

2022-02-05 21:18 UTC, azinit commented on rules/public-api/lite.test.js
> +          import { Four } from "shared/_note/three/four";
Т.е. я вообще думал, что для всех регулярок, где есть сегменты, будет просто еще условие `|_**`, а не прям "читмод" , которые PublicAPI полностью об колено ломает

(если же я что-то не так понимаю в плане ограничений в реализации - дай пож знать)

2022-02-06 08:59 UTC, azinit commented on rules/public-api/lite.js
> +                    `**/?(*)shared/*(${FS_SEGMENTS_REG})`,
[а для бейз конфига не пришлось]

2022-02-06 19:08 UTC, Krakazybik commented on rules/public-api/lite.js
> +                    `**/?(*)shared/*(${FS_SEGMENTS_REG})`,
это я окрылённый псевдобагом с альясами, эксперементировал и закоммитил непотребство, но кстати оно также рабочее =))

2022-02-06 19:09 UTC, Krakazybik commented on rules/public-api/lite.test.js
> +          import { Four } from "shared/_note/three/four";
*картинка кота с лапой у ушка*

2022-02-07 04:28 UTC, azinit approved these changes

2022-02-07 04:28 UTC, azinit commented on rules/public-api/index.js
> +                    `**/*shared/_*/*`
Йее, стало лучше!

2022-02-07 04:28 UTC, azinit commented on rules/public-api/index.test.js
> +        import { Two } from "@shared/_note/two";
Оке, надеюсь вариант `shared/_route` будет валиден)
(либо сам там подправлю уже)

2022-02-07 06:08 UTC, Krakazybik commented on rules/public-api/index.test.js
> +        import { Two } from "@shared/_note/two";
не будет

2022-02-07 06:21 UTC, Krakazybik commented on rules/public-api/index.test.js
> +        import { Two } from "@shared/_note/two";
но теперь будет

2022-02-07 06:27 UTC, merged