LINT-75(feedback): GodMode for _prefix slices
feature-sliced/eslint-config pull request #95
Opened 2022-02-07 21:01 UTC by Krakazybik

## Description
Добавлено:
- Игнорирование ограничений layers-slices для слайсов с _prefix

## References
https://github.com/feature-sliced/eslint-config/discussions/75#discussioncomment-2056223

## Checklist
- [ ] Description added
- [ ] Self-reviewed
- [ ] CI pass

2022-02-08 04:53 UTC, azinit requested changes
Кое-что поправить бы (виноват), а в целом топ 🚀

2022-02-08 04:53 UTC, azinit commented on rules/layers-slices/slices.test.js
> +
[`issue:`](https://conventionalcomments.org/) Лучше бы все же более "каноничные" примеры описывать в тесткейсах, а не выдуманные)
(тем более в референсной ишью такое есть)

[`suggestion:`](https://conventionalcomments.org/) Кажется, так гораздо нагляднее и "стабильнее" будет
```suggestion
        it("should lint without errors in GodMode for pages", async () => {
            const report = await eslint.lintText(`
            import { FooPage } from "pages/foo";
            import { BarPage } from "../bar";
            `,
                {filePath: "src/pages/_router/private.routes.js"});

```

[`thoughts:`](https://conventionalcomments.org/) Как видишь, в указанном примере еще добавил относительные импорты - т.к. их тоже тут не стоит забывать 🤔

2022-02-08 04:53 UTC, azinit commented on rules/layers-slices/slices.test.js
> +    describe("IDDQD boundaries", () => {
[`thoughts:`](https://conventionalcomments.org/) *Потомки разгребая залежи Антарктиды потом долго будут задаваться вопросом, что за IDDQD встречается в писании культа FSD...*

2022-02-08 04:53 UTC, azinit commented on rules/layers-slices/layers.test.js
> +
[`nitpick(critical):`](https://conventionalcomments.org/) Так, тут признаю, виноват что плохо описал - но между слоями мы импорты ПОКА ЕЩЕ не разрешаем благодаря префиксу)

Необходимо сделать только слайсов

2022-02-08 04:53 UTC, azinit commented on rules/layers-slices/index.js
> +        pattern: `${layer}/!(_*){,/*}`,
🤔🤔🤔

![image](https://user-images.githubusercontent.com/42924400/152920166-2f2dddbc-6912-4198-aa98-c6395cfed3f0.png)

2022-02-08 04:53 UTC, azinit commented on rules/layers-slices/slices.test.js
> +
[`suggestion:`](https://conventionalcomments.org/) Плюс, добавил бы еще один тесткейс для компьютедов на всякий (т.к. тесты это и про спеку "эталонности" в том числе)

```js
        it("should lint without errors in GodMode for entities", async () => {
            const report = await eslint.lintText(`
            import { userModel } from "entities/user";
            import { postModel } from "../../Post";
            `,
                {filePath: "src/entities/_computed/UserPost/model.js"});
```

[`thoughts:`](https://conventionalcomments.org/) Тут нужен комментарий, что концепция компьютедов сейчас активно обсуждается кортимой и по сути является экспериментальным подходом по развязыванию сущностей)

> См. подробнее тут
> - https://t.me/feature_sliced/11913
> - https://t.me/feature_sliced/10755

2022-02-08 04:53 UTC, azinit commented on rules/layers-slices/index.js
> +        pattern: `${layer}/!(_*){,/*}`,
Т.е. делаем запрет на импорты для всех слайсов, что начинаются НЕ с "_"?

Или как это трактовать?

2022-02-09 19:31 UTC, Krakazybik commented on rules/layers-slices/index.js
> +        pattern: `${layer}/!(_*){,/*}`,
ну да, но тут про разрешаем )

2022-02-10 05:39 UTC, azinit approved these changes
🔥 🔥 🔥

2022-02-10 05:39 UTC, azinit commented on rules/layers-slices/index.js
> +        pattern: `${layer}/_*`,
[`thoughts:`](https://conventionalcomments.org/) Чет резко усложнилась реализация))

Надеюсь, что оправданно

2022-02-10 05:39 UTC, azinit commented on rules/layers-slices/layers.test.js
> +            assert.strictEqual(report[0].errorCount, 1);
[`thoughts:`](https://conventionalcomments.org/) Уже триггернуться хотел))

2022-02-10 05:39 UTC, azinit commented on rules/layers-slices/layers.test.js
> +            `,
[`praise:`](https://conventionalcomments.org/) Круто, что дополнительно пролинтил основные ограничения для GodMode!

2022-02-10 07:05 UTC, merged