LINT-86(Feedback): Refine bootstraping of linting
feature-sliced/eslint-config pull request #98
Opened 2022-02-17 21:00 UTC by Krakazybik

## Description

## References

## Checklist
- [ ] Description added
- [ ] Self-reviewed
- [ ] CI pass

2022-02-17 21:06 UTC, Krakazybik commented on cli.js
> +function getPkgMangerType() {
получаем тип пакетного менеджера

2022-02-17 21:06 UTC, Krakazybik commented on cli.js
> +    }
Из ошибок думаю понятно о чем тут.

2022-02-17 21:06 UTC, Krakazybik commented on cli.js
> +async function exec(cmd, pkgManager = null) {
функция запускающая консольные командочки

2022-02-17 21:06 UTC, Krakazybik commented on cli.js
> +}
Получаем из МЯВА package.json, Также мява будем потом использовать для наведения красивостей. Он это умеет.

https://www.npmjs.com/package/meow

2022-02-17 21:06 UTC, Krakazybik commented on cli.js
> +}
Из названия думаю всё ясно, хз че тут комментить.
Хок, который вызывает наш пакетный менеджер с забинженой командой, в нашем случае install

2022-02-17 21:08 UTC, Krakazybik commented on cli.js
> +}
название поправлю))

2022-02-18 05:03 UTC, azinit requested changes

2022-02-18 05:03 UTC, azinit commented on package.json
> +    "eslint-plugin-import": "2.25.4"
[`question:`](https://conventionalcomments.org/) А почему пришлось уточнить версию? 🤔 

Разве cli не подхватывает в общем формате? `>=2`

2022-02-18 05:03 UTC, azinit commented on package.json
> +  }
[`issue(critical):`](https://conventionalcomments.org/) Т.е. люди при установке пакета должны будут установить себе зависимости для cli? Оч сомнительно)

[`suggestion(critical):`](https://conventionalcomments.org/) Кмк это все еще девдепсы, а сам cli будет отдельным пакетом в npm 🤔 

[`thoughts:`](https://conventionalcomments.org/) Было бы неплохо кста, если бы в README базово описал как-нибудь, как эта штука должна работать

2022-02-18 05:03 UTC, azinit commented on cli.js
> +}
[`question:`](https://conventionalcomments.org/) Чисто интересно -  а на что ориентировался при написании?)

2022-02-18 06:55 UTC, Krakazybik commented on cli.js
> +}
Ни на что =)

2022-02-18 06:56 UTC, Krakazybik commented on package.json
> +  }
Почему он должны установить? Объясни? Rollup, build, terser и у нас "бинарник".

2022-02-18 08:38 UTC, Krakazybik commented on package.json
> +    "eslint-plugin-import": "2.25.4"
в консоле ">" это управление пайпами, надо изолировать вначале этот символ.

2022-02-20 15:47 UTC, azinit commented on cli.js
> +}
Так тыж сам кинул PR 😄

2022-02-20 15:47 UTC, azinit commented on package.json
> +    "eslint-plugin-import": "2.25.4"
Не понял ответ)

2022-02-20 15:50 UTC, Krakazybik commented on package.json
> +    "eslint-plugin-import": "2.25.4"
менеджеры пакетов не понимают логические (><=) версии при установке через add/install =(

2022-02-20 15:50 UTC, azinit commented on package.json
> +  }
> В след раз буду кидать гистом только cli.js, чтоб внимание не размазывалось на вроде очевидные и понятные вещи) УууУуЪ!

Ну вот да, поэтому драфты лучше и не кидать на ревью))

Только если коммит/гист кода для крит. моментов

2022-02-20 15:52 UTC, azinit commented on cli/cli.js
> +    return _.merge(cli.pkg.dependencies, cli.pkg.devDependencies);
[`thoughts:`](https://conventionalcomments.org/) ууу, мощная артиллерия пошла)

2022-02-20 15:52 UTC, azinit commented on packages/cli/README.md
> +# @feature-sliced/
[`praise:`](https://conventionalcomments.org/) Спасиб за описание!

2022-02-20 15:59 UTC, azinit commented on packages/cli/package.json
> +    "rollup-plugin-terser": "^7.0.2"
[`question:`](https://conventionalcomments.org/) А стоило ли так упарываться ради пакета, который через npx будет запускаться? 🤔 


[`thoughts:`](https://conventionalcomments.org/) Тот же [eslint-kit/cli](https://github.com/eslint-kit/cli/blob/master/package.json#L21) вообще только tsc запускает при билде

А всякие минификации и прочие танцы с бубном - как будто рили out-of-scope
[`question:`](https://conventionalcomments.org/) (особенно `pnpm-lock` который тоже неясно зачем тут нужен)

2022-02-20 15:59 UTC, azinit commented on package.json
> +    "eslint-plugin-import": "2.25.4"
Все еще не понял, почему это должно затрагивать package.json наш))

2022-02-20 15:59 UTC, azinit commented on package.json
> +    "eslint-plugin-import": "2.25.4"
Правильно понял - что ты просто на нашем package.json тренился, и поэтому в диффе эти депсы были затронуты?

2022-02-20 16:02 UTC, Krakazybik commented on package.json
> +    "eslint-plugin-import": "2.25.4"
да да) всё верно, это был испытательный полигон, в итоге вынесено в отдельный пакет в packages

2022-02-20 16:04 UTC, Krakazybik commented on packages/cli/package.json
> +    "rollup-plugin-terser": "^7.0.2"
не понял немного, можешь пояснить?

2022-02-20 16:04 UTC, azinit reviewed
Пока выглядит чет как хоть и "проработанная" но "жирная" реализация для простого `npm install`))

Если бы кинул гифку того, как это работает в итоге, не помешало бы
(чуть позже еще гляну, подетальней)

2022-02-20 16:04 UTC, azinit commented on packages/cli/src/index.js
> +};
[`question:`](https://conventionalcomments.org/) Это тут ты имел в виду, что "<>" не распознаются для установки версий?

2022-02-20 16:04 UTC, azinit commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
[`thoughts:`](https://conventionalcomments.org/) Чет жесть, если ради "казалось бы" простой установки зависимостей, пришлось несколько модулей на 300-400 строчек наплодить 😱

2022-02-20 16:04 UTC, azinit commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
Хотя и понимаю, что "ты старался")

2022-02-20 16:06 UTC, azinit commented on packages/cli/package.json
> +    "rollup-plugin-terser": "^7.0.2"
> не понял немного, можешь пояснить?

Поясняю - "rollup (и любой другой сборщик) для простого cli, который никто устанавливать не будет - не нужен :)"
(у нас даже для eslint-config сборщика пока нет, т.к. это devDeps)

2022-02-20 16:06 UTC, Krakazybik commented on packages/cli/package.json
> +    "rollup-plugin-terser": "^7.0.2"
> [thoughts:](https://conventionalcomments.org/) Тот же [eslint-kit/cli](https://github.com/eslint-kit/cli/blob/master/package.json#L21) вообще только tsc запускает при билде

И на выходе получаем ts файл, для запуска которого нужен typescript, верно?

2022-02-20 16:08 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
попробуй установи вручную из консоли с > <

2022-02-20 16:08 UTC, Krakazybik commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
там 200 даже нет

2022-02-20 16:12 UTC, Krakazybik commented on packages/cli/package.json
> +    "rollup-plugin-terser": "^7.0.2"
Ну мб и лишнее, думал о том, чтоб получить на выходе сбандленный js без лишних зависимостей в одном файле

2022-02-20 16:33 UTC, Krakazybik commented
> Пока выглядит чет как хоть и "проработанная" но "жирная" реализация для простого npm install))

А нам надо что? Не понимаю тогда к чему все диолги, о том что нам слишком много кнопок надо нажать чтоб установить.


> Пока что же крутится мысль "Блин. А нельзя никак упростить это все? :DD"

Упростить в плане? 



> Если бы кинул гифку того, как это работает в итоге, не помешало бы
(чуть позже еще гляну, подетальней)


https://user-images.githubusercontent.com/1334019/154853116-5374d7b6-1293-42ec-baad-937fd1b24f97.mp4

2022-02-20 16:35 UTC, azinit commented on packages/cli/src/index.js
> +};
> попробуй установи вручную из консоли с > <

Нууу, типа `eslint-plugin-boundaries@^2.8.0` должно сработать 🤔

2022-02-20 16:35 UTC, azinit commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
> там 200 даже нет

Ну это как считать))

![image](https://user-images.githubusercontent.com/42924400/154853418-24556382-180f-49d4-8e16-423240e19a5f.png)

2022-02-20 16:36 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
Не знаю как у тебя, но у меня ничего такого не работает

2022-02-20 16:37 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
А если не работает у меня, но работает у тебя, то это уже повод к тому чтоб такими вещами не пользоваться

2022-02-20 16:37 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
`yarn add eslint-plugin-boundaries@^2.8.0`

2022-02-20 16:38 UTC, azinit commented
> А нам надо что? Не понимаю тогда к чему все диолги, о том что нам слишком много кнопок надо нажать чтоб установить.

> Упростить в плане?

Ну просто у меня в голове было что-то простое на уровне простого bash-скрипта не больше 100 строчек))

А тут и роллап, и несколько доп.модулей для работы скрипта, и pnpm еще зачем-то... (хотя ясно что можно было и без pnpm)

Поэтому и говорю, что надо пересмотреть еще раз требования по задаче и понять - точно ли никак это проще нельзя было сделать 🤔 
(это не для обесценивания твоих стараний, а чтобы нам же меньше потом проблем по поддержке и стабилизации этого было)

>  2022-02-20.19-28-53.mp4 

Но выглядит красиво красиво конечно, тут ничего не попишешь))

2022-02-20 16:39 UTC, Krakazybik commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
Вычти ридми, package.json, rollup.conf  пожалуйста)

2022-02-20 16:39 UTC, azinit commented on packages/cli/package.json
> +    "rollup-plugin-terser": "^7.0.2"
> > [thoughts:](https://conventionalcomments.org/) Тот же [eslint-kit/cli](https://github.com/eslint-kit/cli/blob/master/package.json#L21) вообще только tsc запускает при билде
> 
> И на выходе получаем ts файл, для запуска которого нужен typescript, верно?

Так нет же, он в js конвертит по идее как раз 🤔 
(т.е. билд нужен только для конвертации ts в js, и больше ничего)

2022-02-20 16:40 UTC, azinit commented on packages/cli/package.json
> +    "rollup-plugin-terser": "^7.0.2"
> Ну мб и лишнее, думал о том, чтоб получить на выходе сбандленный js без лишних зависимостей в одном файле

Просто чуть оверинжинирингом попахивает)

Хоть и благие намерения, но потом в такой усложненной "инфраструктуре" для скрипта - задолбаемся что-то править/улучшать
(хотя мб и утрирую, просто роллап для скрипта прям сильно глаза режет)

2022-02-20 16:41 UTC, azinit commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
Все равно много как будто остается))

Но чуть позже гляну еще более объективно

2022-02-20 16:41 UTC, azinit commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
Ясно дело, что тут не "за каждую строчку кода" удушить готов)

2022-02-20 16:43 UTC, azinit commented on packages/cli/src/index.js
> +};
Гляну позж, хотя это built-in возможность по идее 🤔 

https://www.carlrippon.com/upgrading-npm-dependencies/

2022-02-20 16:46 UTC, Krakazybik commented
> Ну просто у меня в голове было что-то простое на уровне простого bash-скрипта не больше 100 строчек))


Ога, для виндовс. Bash скрип. :rofl: (p.s. я понимаю что ты про js))  А потом мы захотим баш скриптом патчить конфиг, или выбирать нужные опции конфига, и давай теперь новый баш скрипт выдумывать. А здесь всё в принципе расширяемо. На любом этапе можно выполнить любую команду добавив нужный HOF, для патчинга, добавь строчку в questions и тд.

Полюбому опять будет кому-то сложно и он скажет я не хочу дописывать lite/experemental, пусть оно само делает.


> А тут и роллап, и несколько доп.модулей для работы скрипта, и pnpm еще зачем-то... (хотя ясно что можно было и без pnpm)

Это из расчета на то, что ты утащишь в отдельный пакет, т.к. зачем нам зависимости лишние для eslint-config?

2022-02-20 16:49 UTC, Krakazybik commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
> Ясно дело, что тут не "за каждую строчку кода удушить готов)"

Чето не похоже =((

2022-02-20 18:27 UTC, Krakazybik commented
Мона вывод инфы оставить

https://user-images.githubusercontent.com/1334019/154857977-af631b71-8cc7-405d-a779-42c03075ac42.mp4

2022-02-20 18:28 UTC, Krakazybik commented
Мона это в принципе слепить в одну команду )) Но тогда не так эффекто смотреться будет xD

2022-02-20 18:41 UTC, Krakazybik commented
Пока слепил в js и ts отдельно

2022-02-20 19:09 UTC, azinit commented on packages/cli/src/index.js
> +};
> Не знаю как у тебя, но у меня ничего такого не работает

Ну как бэ....)))

<table>
<td>

yarn
![image](https://user-images.githubusercontent.com/42924400/154859673-38bb60b0-c71e-4c9a-b7ab-ed7ace33b3da.png)

</td>
<td>

npm
![image](https://user-images.githubusercontent.com/42924400/154859856-995963a2-2d8a-484f-895d-995200c0f01c.png)

</td>
</table>

2022-02-20 19:11 UTC, azinit commented on packages/cli/src/index.js
> +};
> А если не работает у меня, но работает у тебя, то это уже повод к тому чтоб такими вещами не пользоваться


Тип это настолько нативная штука встроенная в любой package-manager, что я бы тут не сомневался особо и пихал `^{current-package-version`, в соответствие с package.json

А лучше, чтоб не дублировать - сразу брать из package.json версии, и если формат `>=` не подходит - то лучше сразу в package.json поправить - т.к. то же самое может возникнуть и если пер-депсы самостоятельно устанавливать кмк 🤔

2022-02-20 19:11 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
![image](https://user-images.githubusercontent.com/1334019/154859938-bddb7c14-364a-4d74-8044-fc8dd9db026f.png)

2022-02-20 19:12 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
мне надо через изолированный 
![image](https://user-images.githubusercontent.com/1334019/154859962-29723e09-35da-4bc8-998e-5d9524bd5424.png)

2022-02-20 19:13 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
т.к. в юниксе > < это пайпы и остальное тоже юзается

2022-02-20 19:13 UTC, azinit commented on packages/cli/src/index.js
> +};
Можно бы оставить и вариант с `latest` конечн, т.к. по сути тот же latest устанавливается и при ручной установке пакетов... Но более правильно, кмк, все же брать ТОЧНО совместимую версию)
*(а то обновят мажор с ломающим API, а пользователь и не поймет в чем проблема)*

2022-02-20 19:13 UTC, Krakazybik commented on packages/cli/src/index.js
> +};
ну или всё в ковычках

2022-02-20 19:14 UTC, azinit commented on packages/cli/src/index.js
> +const { runCmdFactory, exec } = require("./run");
> > Ясно дело, что тут не "за каждую строчку кода удушить готов)"
> 
> Чето не похоже =((

Тебе кажется)))

Я еще "любя"

2022-02-20 19:16 UTC, azinit commented on packages/cli/src/index.js
> +};
Ладно, хрен с ним)

Давай latest пока оставим **(попроще)**, но вангую баги от пользователей

2022-02-20 19:18 UTC, azinit commented
> она вывод инфы оставить

Пересмотрел оба скринкаста - но не увидел разницы, честно честно)))

Или то что во "втором" еще показывается как устанавливается каждая зависимость отдельно?

2022-02-20 19:34 UTC, azinit approved these changes
В целом норм, хотя по имплементации местами хочется прям придираться если сильно вчитываться

Но в рамках задачи некрит)

Самое главное - что довел до конца и не выгорел (надеюсь) пока писал
Остальное - разберемся)

Еще раз спс, что с усердностью довел PR до конца и описал ридмиху!
(хотя надеюсь оба уже понимаем, что драфты лучше не кидать для ревью 😏 )

2022-02-20 19:34 UTC, azinit commented on packages/cli/pnpm-lock.yaml
> +lockfileVersion: 5.3
[`nitpick(non-blocking, wtf):`](https://conventionalcomments.org/) Некрит конечно, но оч странно, в репозитории где уже `yarn.lock` есть, тащить для внутреннего пакета внезапно pnpm 🤔 

Я бы удалил его нафиг и консистентности всеж придерживался

2022-02-20 19:34 UTC, azinit commented on packages/cli/package.json
> +{
[`praise:`](https://conventionalcomments.org/) Кста не сразу заметил - но прикольно, что сразу директорию `packages` уже выделил

processor наверное тоже туда засуну после мерджа)

2022-02-20 19:34 UTC, azinit commented on packages/cli/src/index.js
> +}
[`nitpick(non-blocking, чисто-придраться-к-имплементации):`](https://conventionalcomments.org/) Некрит, но тут бы обычный `for..of` подошел бы лучше, т.к если сработает одно из условий - то сразу будет выход из основной функции

А с редьюсом - он еще будет гоняться)
(хоть и "декларативненько")

> ~~Экономим на спичках!~~ Но вообще просто рили в особо жирных package.json может вызывать перф-фризы

2022-02-20 19:34 UTC, azinit commented on packages/cli/src/index.js
> +ui(bootstrap, isTypeScriptProject(getUserDeps(cli)));
[`nitpick(non-blocking, чисто-придраться-к-имплементации):`](https://conventionalcomments.org/) Если прям придираться - то некоторые функции я бы тоже в другие модуля вынес)

Оставил бы здесь чисто бутстрапинг и обертку  что в конце файла

А то пока ощущается чисто как полотнище функций, которые неясно чтобы что)

2022-02-20 19:34 UTC, azinit commented on packages/cli/src/log.js
> +
[`thoughts:`](https://conventionalcomments.org/) Ну прям тотальная артиллерия!)

2022-02-20 19:35 UTC, Krakazybik commented
> Пересмотрел оба скринкаста - но не увидел разницы, честно честно)))
Или то что во "втором" еще показывается как устанавливается каждая зависимость отдельно?

Ога, типо красивенькое.

2022-02-20 19:35 UTC, Krakazybik commented on packages/cli/src/log.js
> +
Шо такэ? Кросивое же!

2022-02-20 19:38 UTC, azinit commented
> > Пересмотрел оба скринкаста - но не увидел разницы, честно честно)))
> > Или то что во "втором" еще показывается как устанавливается каждая зависимость отдельно?
> 
> Ога, типо красивенькое.

Ну чисто субъективно - мне больше нравится более минималистичный варик, где меньше лишней инфы

Но если оч хочешь - то можно под каким-нибудь флагом `--verbose` чтобы выводилось с логами такими)
(а по дефолту - коротенько, как на первом скринкасте)

2022-02-20 19:38 UTC, Krakazybik commented on packages/cli/src/index.js
> +}
я могу научить выходить из редьюса, но тут это какжется лишнее xD

2022-02-20 19:38 UTC, azinit commented
@Krakazybik Влей как сочтешь нужным)
(из критов прям - pnpm-lock для cli разве что - но там если что сам его удалю наверн)

2022-02-20 19:39 UTC, azinit commented on packages/cli/src/index.js
> +}
Именно что "лишнее")

2022-02-20 19:39 UTC, Krakazybik commented on packages/cli/pnpm-lock.yaml
> +lockfileVersion: 5.3
о, это вообще надо, т.к. pnpm умеет в монорепы из коробки, мб ярн анигилируем?

2022-02-20 19:41 UTC, azinit commented on packages/cli/pnpm-lock.yaml
> +lockfileVersion: 5.3
При наших масштабах - **нафиг монорепы))**

От них только больше проблем, а хотелось бы, что если потом придет контрибьютор внешний - он не офигевал от сложности сетапинга окружения

2022-02-20 19:42 UTC, Krakazybik commented on packages/cli/src/index.js
> +ui(bootstrap, isTypeScriptProject(getUserDeps(cli)));
Я хотел, но ты виноват короче xD расстроил меня, сказал что модулей наплодил xD

2022-02-20 19:42 UTC, azinit commented on packages/cli/src/index.js
> +ui(bootstrap, isTypeScriptProject(getUserDeps(cli)));
Мне самому надо было пройти еще через 5 стадий отрицания))

2022-02-20 19:44 UTC, Krakazybik commented
> Ну чисто субъективно - мне больше нравится более минималистичный варик, где меньше лишней инфы
Плюсик.

2022-02-20 20:05 UTC, Krakazybik commented on packages/cli/src/index.js
> +ui(bootstrap, isTypeScriptProject(getUserDeps(cli)));
пока так пораскидал, потому подумаю как лучше сделать =)

2022-02-20 20:13 UTC, azinit approved these changes
Ну красотень прям)

> Заметь, с yarn и кол-во строк снизилось 😏 
![image](https://user-images.githubusercontent.com/42924400/154862349-c455c883-a71c-493a-ae0b-322ba6828bbb.png)

2022-02-20 20:13 UTC, azinit commented on packages/cli/src/index.js
> +    for (const dep of userDeps) {
красотень!

2022-02-20 20:13 UTC, azinit commented on packages/cli/package.json
> +    "lodash": "^4.17.21",
[`question:`](https://conventionalcomments.org/) Так они же все равно для запуска cli нужны, не?))

2022-02-20 20:13 UTC, azinit commented on packages/cli/src/index.js
> +const meow = require("meow");
[`praise:`](https://conventionalcomments.org/) Круто раскидал!

2022-02-20 20:13 UTC, Krakazybik commented on packages/cli/package.json
> +    "lodash": "^4.17.21",
с роллапом, нет ) но то потестить ещё надо

2022-02-20 20:14 UTC, Krakazybik commented on packages/cli/package.json
> +    "lodash": "^4.17.21",
ну это если мы его оставим xD

2022-02-20 20:23 UTC, merged